// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REST_EF_06_Migrazioni.Context;

#nullable disable

namespace REST_EF_06_Migrazioni.Migrations
{
    [DbContext(typeof(CinemaContext))]
    [Migration("20241029091429_AggiuntaCategorie")]
    partial class AggiuntaCategorie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("REST_EF_06_Migrazioni.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CategoriaID");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("REST_EF_06_Migrazioni.Models.Film", b =>
                {
                    b.Property<int>("FilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmID"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<string>("Autore")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Distribuzione")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("FilmID");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("Proiezioni");
                });

            modelBuilder.Entity("REST_EF_06_Migrazioni.Models.Film_Categoria", b =>
                {
                    b.Property<int>("FilmCategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmCategoriaID"));

                    b.Property<int>("CategoriaRIF")
                        .HasColumnType("int");

                    b.Property<int>("FilmRIF")
                        .HasColumnType("int");

                    b.HasKey("FilmCategoriaID");

                    b.HasIndex("CategoriaRIF");

                    b.HasIndex("FilmRIF");

                    b.ToTable("Film_Categoria");
                });

            modelBuilder.Entity("REST_EF_06_Migrazioni.Models.Film_Categoria", b =>
                {
                    b.HasOne("REST_EF_06_Migrazioni.Models.Categoria", "CategoriaNavigation")
                        .WithMany("FilmCatList")
                        .HasForeignKey("CategoriaRIF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("REST_EF_06_Migrazioni.Models.Film", "FilmNavigation")
                        .WithMany("FilmCatList")
                        .HasForeignKey("FilmRIF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaNavigation");

                    b.Navigation("FilmNavigation");
                });

            modelBuilder.Entity("REST_EF_06_Migrazioni.Models.Categoria", b =>
                {
                    b.Navigation("FilmCatList");
                });

            modelBuilder.Entity("REST_EF_06_Migrazioni.Models.Film", b =>
                {
                    b.Navigation("FilmCatList");
                });
#pragma warning restore 612, 618
        }
    }
}
